import type { FilterButtonStyleParams } from "./types"
import { cn } from "@/shared/utils/cn"

export const filterStyles = {
	filterPanel: cn(
		"relative",
		"z-20",
		"flex",
		"flex-col",
		"gap-2",
		"rounded-lg",
		"border",
		"border-[var(--border-color)]",
		"bg-[var(--background-3)]",
		"p-2.5",
	),
	filterRow: cn(
		"flex",
		"items-center",
		"justify-between",
		"gap-2",
	),
	filterLabel: cn(
		"shrink-0",
		"text-[10px]",
		"font-semibold",
		"text-[var(--font-color-secondary)]",
	),
	filterButtons: cn(
		"flex",
		"min-w-0",
		"flex-wrap",
		"justify-end",
		"gap-1",
	),
	filterButton: ({ selected }: FilterButtonStyleParams) => cn(
		"rounded-md",
		"border",
		"px-2",
		"py-0.5",
		"text-[10px]",
		"font-semibold",
		"transition",
		"focus-visible:outline-none",
		"focus-visible:ring-2",
		"focus-visible:ring-[var(--focus-ring-color)]",
		"disabled:cursor-not-allowed",
		"disabled:opacity-50",
		selected ?
			["border-[var(--button-color)]", "bg-[var(--button-color)]", "text-[var(--button-font-color)]"] :
			["border-[var(--border-color-strong)]", "bg-[var(--background-2)]", "text-[var(--font-color-secondary)]", "hover:bg-[var(--background-3)]"],
	),
	filterInputRow: cn(
		"flex",
		"items-end",
		"gap-1.5",
	),
	filterInputContainer: cn(
		"relative",
		"min-w-0",
		"flex-1",
	),
	clearButton: cn(
		"mb-px",
		"shrink-0",
		"px-2.5",
		"text-[10px]",
	),
	history: cn(
		"absolute",
		"inset-x-0",
		"top-full",
		"z-30",
		"mt-1",
		"max-h-48",
		"orqeto-scroll-area",
		"overflow-y-auto",
		"rounded-lg",
		"border",
		"border-[var(--border-color)]",
		"bg-[var(--background-2)]",
		"p-1",
		"shadow-xl",
	),
	historyTitle: cn(
		"px-2",
		"py-1",
		"text-[9px]",
		"font-bold",
		"uppercase",
		"tracking-wide",
		"text-[var(--font-color-subtle)]",
	),
	historyItem: cn(
		"flex",
		"items-center",
		"gap-1",
		"rounded-md",
		"hover:bg-[var(--background-3)]",
	),
	historyValue: cn(
		"flex",
		"min-w-0",
		"flex-1",
		"flex-col",
		"items-start",
		"px-2",
		"py-1.5",
		"text-left",
	),
	historyPattern: cn(
		"max-w-full",
		"truncate",
		"text-[11px]",
		"font-medium",
		"text-[var(--font-color-secondary)]",
	),
	historyMeta: cn(
		"text-[9px]",
		"text-[var(--font-color-subtle)]",
	),
	historyDelete: cn(
		"mr-1",
		"flex",
		"h-6",
		"w-6",
		"shrink-0",
		"items-center",
		"justify-center",
		"rounded-md",
		"text-[var(--font-color-subtle)]",
		"transition",
		"hover:bg-[var(--background-3)]",
		"hover:text-[var(--font-color-secondary)]",
	),
} as const
