import type { CollapseInnerStyleParams } from "./types"
import { cn } from "@/shared/utils/cn"

export const layoutStyles = {
	embedded: cn(
		"mt-3",
		"flex",
		"flex-col",
		"gap-2.5",
	),
	container: cn(
		"relative",
		"flex",
		"flex-col",
		"rounded-xl",
		"border",
		"border-[var(--border-color)]",
		"bg-[var(--background-2)]",
		"p-3",
		"shadow-sm",
	),
	toggleButton: cn(
		"absolute",
		"right-3",
		"top-3",
		"z-40",
		"flex",
		"h-7",
		"w-7",
		"items-center",
		"justify-center",
		"rounded-md",
		"border",
		"border-[var(--border-color)]",
		"bg-[var(--background-2)]",
		"text-[var(--font-color-muted)]",
		"shadow-sm",
		"backdrop-blur-sm",
		"transition",
		"hover:bg-[var(--background-3)]",
		"hover:text-[var(--font-color)]",
		"focus-visible:outline-none",
		"focus-visible:ring-2",
		"focus-visible:ring-[var(--focus-ring-color)]",
		"motion-reduce:transition-none",
	),
	collapseRegion: cn(
		"relative",
		"z-20",
	),
	collapseInner: ({ expanded }: CollapseInnerStyleParams) => cn(
		"relative",
		"z-20",
		"flex",
		"min-h-0",
		"flex-col",
		"pt-2.5",
		expanded ?
			"overflow-visible" :
			"overflow-hidden",
	),
	header: cn(
		"mb-2.5",
		"flex",
		"items-start",
		"gap-2.5",
		"pr-9",
	),
	headerIcon: cn(
		"flex",
		"h-7",
		"w-7",
		"shrink-0",
		"items-center",
		"justify-center",
		"rounded-lg",
		"bg-[var(--button-color)]",
		"text-[var(--button-font-color)]",
	),
	sectionTitle: cn(
		"text-[13px]",
		"font-bold",
		"text-[var(--font-color)]",
	),
	sectionDescription: cn(
		"mt-0.5",
		"text-[11px]",
		"leading-4",
		"text-[var(--font-color-muted)]",
	),
} as const
