import type { WorkspaceState } from "./useWorkspaceState"

export function createContextWorkspace<Actions extends Record<string, unknown>>(
	state: WorkspaceState,
	actions: Actions,
) {
	const {
		autoClearAfterExport,
		autoCopyContextAfterAdd,
		clearLogsAfterCopy,
		cancellableContextOperationKind,
		cancelledContextOperationKind,
		closeExplorerOnFolderClose,
		contextFilterHistory,
		contextFilterMode,
		contextFilterTarget,
		contextHistory,
		contextPathFilter,
		contextPathFilterError,
		currentPreparedDiagnosticContexts,
		currentPreparedGitCommitContext,
		currentPreparedValidationCommandContexts,
		diagnosticCapabilities,
		diagnosticContextKind,
		files,
		fullProjectContextSummary,
		generatedContentSize,
		isApplying,
		isCancellableContextOperationCancelled,
		isFixingLint,
		isGeneratingCommitContext,
		isGeneratingProjectContext,
		isGitRepository,
		isInspectingProjectContext,
		isProcessing,
		isReady,
		locale,
		notice,
		openExplorerOnProjectOpen,
		overlayUndoHistory,
		pathSelectionContent,
		pathsOnly,
		pendingGitPatch,
		pendingOverlay,
		publishNotice,
		rootFolder,
		validationCommandKind,
		workMode,
	} = state

	return {
		rootFolder,
		locale,
		workMode,
		contextPathFilter,
		contextFilterTarget,
		contextFilterMode,
		contextPathFilterError,
		contextFilterHistory,
		contextHistory,
		pathsOnly,
		autoCopyContextAfterAdd,
		autoClearAfterExport,
		clearLogsAfterCopy,
		openExplorerOnProjectOpen,
		closeExplorerOnFolderClose,
		files,
		notice,
		publishNotice,
		isReady,
		isProcessing,
		isApplying,
		isGitRepository,
		isGeneratingCommitContext,
		gitCommitContextByteCount: currentPreparedGitCommitContext?.byteCount ?? null,
		gitCommitContextVariant: currentPreparedGitCommitContext?.variant ?? null,
		gitCommitComparisonStats: currentPreparedGitCommitContext?.variant === "compare" ?
			currentPreparedGitCommitContext.comparisonStats :
			null,
		gitCommitComparisonSelection: currentPreparedGitCommitContext?.variant === "compare" ?
			{
				from: currentPreparedGitCommitContext.fromCommit,
				to: currentPreparedGitCommitContext.toCommit,
			} :
			null,
		diagnosticContextByteCounts: {
			typecheck: currentPreparedDiagnosticContexts.typecheck?.byteCount ?? null,
			eslint: currentPreparedDiagnosticContexts.eslint?.byteCount ?? null,
		},
		validationCommandContextByteCounts: {
			lintfix: currentPreparedValidationCommandContexts.lintfix?.byteCount ?? null,
			test: currentPreparedValidationCommandContexts.test?.byteCount ?? null,
		},
		isGeneratingProjectContext,
		isInspectingProjectContext,
		fullProjectContextSummary,
		diagnosticContextKind,
		validationCommandKind,
		isFixingLint,
		cancellableContextOperationKind,
		cancelledContextOperationKind,
		isCancellableContextOperationCancelled,
		diagnosticCapabilities,
		pendingOverlay,
		pendingGitPatch,
		overlayUndoHistory,
		generatedContent: pathSelectionContent,
		generatedContentSize,
		...actions,
	}
}
