export type BusinessRuleOwner = "node" | "rust"

export interface BusinessRuleDefinition {
	id: string
	description: string
	owner: BusinessRuleOwner
	evidenceFile: string
	evidenceToken: string
}

export const businessRules: readonly BusinessRuleDefinition[] = [
	{
		id: "BR-CTX-001",
		description: "Active manual Context keeps path references and discards source content from long-lived selection state.",
		owner: "node",
		evidenceFile: "scripts/business-rules/context-selection.test.mts",
		evidenceToken: "BR-CTX-001",
	},
	{
		id: "BR-CTX-002",
		description: "Re-adding an already selected path reports it as already present and never replaces selection state with supplied content.",
		owner: "node",
		evidenceFile: "scripts/business-rules/context-selection.test.mts",
		evidenceToken: "BR-CTX-002",
	},
	{
		id: "BR-CTX-003",
		description: "Re-sending a selection may add newly discovered paths while preserving deduplication of existing paths.",
		owner: "node",
		evidenceFile: "scripts/business-rules/context-selection.test.mts",
		evidenceToken: "BR-CTX-003",
	},
	{
		id: "BR-CTX-004",
		description: "Context materialization reads the current filesystem bytes rather than selection-time bytes.",
		owner: "rust",
		evidenceFile: "src-tauri/src/lib.rs",
		evidenceToken: "br_ctx_004_materialization_reads_current_content_instead_of_selection_time_content",
	},
	{
		id: "BR-CTX-005",
		description: "Manual Context selection discovers path membership without opening or decoding source file bodies.",
		owner: "rust",
		evidenceFile: "src-tauri/src/lib.rs",
		evidenceToken: "br_ctx_005_selection_keeps_binary_file_as_reference_without_materializing_body",
	},
	{
		id: "BR-CTX-006",
		description: "Missing or newly ignored selected members are unavailable at materialization and stale selection-time bytes are never substituted.",
		owner: "rust",
		evidenceFile: "src-tauri/src/lib.rs",
		evidenceToken: "br_ctx_006_unavailable_selected_members_never_use_stale_content",
	},
	{
		id: "BR-CTX-007",
		description: "Files created after a folder was selected remain outside active Context until that folder or file is explicitly sent again.",
		owner: "node",
		evidenceFile: "scripts/business-rules/context-selection.test.mts",
		evidenceToken: "BR-CTX-007",
	},
	{
		id: "BR-CTX-008",
		description: "Manual Clear discards active Context even when selected paths are unavailable, while skipping incomplete history snapshots.",
		owner: "node",
		evidenceFile: "scripts/business-rules/generated-context-workflow.test.mts",
		evidenceToken: "BR-CTX-008",
	},
	{
		id: "BR-HISTORY-001",
		description: "Routine Context history listing transports metadata only and never includes archived content blobs.",
		owner: "rust",
		evidenceFile: "src-tauri/src/config_database.rs",
		evidenceToken: "br_history_001_history_listing_returns_metadata_without_content_blob",
	},
	{
		id: "BR-HISTORY-002",
		description: "A single Context history snapshot is loaded lazily and reproduced byte-for-byte when requested.",
		owner: "rust",
		evidenceFile: "src-tauri/src/config_database.rs",
		evidenceToken: "br_history_002_history_content_is_loaded_lazily_and_exactly",
	},
	{
		id: "BR-HISTORY-003",
		description: "Routine React history state is metadata-only and copy loads one archived snapshot lazily on demand.",
		owner: "node",
		evidenceFile: "scripts/business-rules/history-lazy.test.mts",
		evidenceToken: "BR-HISTORY-003",
	},
	{
		id: "BR-HISTORY-004",
		description: "History download resolves archived content inside the Rust backend instead of routing the blob through React state.",
		owner: "node",
		evidenceFile: "scripts/business-rules/history-lazy.test.mts",
		evidenceToken: "BR-HISTORY-004",
	},
	{
		id: "BR-RES-001",
		description: "A traversal resource budget accepts work exactly at its configured limits.",
		owner: "rust",
		evidenceFile: "src-tauri/src/resource_limits.rs",
		evidenceToken: "br_res_001_budget_accepts_values_at_the_limit",
	},
	{
		id: "BR-RES-002",
		description: "A traversal resource budget rejects the first file, directory, entry, or overlong path beyond its configured limit.",
		owner: "rust",
		evidenceFile: "src-tauri/src/resource_limits.rs",
		evidenceToken: "br_res_002_budget_rejects_the_first_value_over_each_limit",
	},
	{
		id: "BR-RES-003",
		description: "Large-project discovery ceilings are 500,000 files, 1,000,000 directories, and 1,500,000 combined entries.",
		owner: "rust",
		evidenceFile: "src-tauri/src/resource_limits.rs",
		evidenceToken: "br_res_003_large_project_ceiling_values_are_stable",
	},
	{
		id: "BR-RES-004",
		description: "Large-project discovery accepts each exact ceiling and rejects the first item beyond it without allocating project contents.",
		owner: "rust",
		evidenceFile: "src-tauri/src/resource_limits.rs",
		evidenceToken: "br_res_004_large_ceiling_and_limit_plus_one_are_bounded_without_allocation",
	},
	{
		id: "BR-RES-005",
		description: "Machine resource policy caps background I/O parallelism and keeps stream buffers bounded on every machine size.",
		owner: "rust",
		evidenceFile: "src-tauri/src/resource_limits.rs",
		evidenceToken: "br_res_005_machine_policy_caps_parallelism_and_buffer_size",
	},
	{
		id: "BR-RES-006",
		description: "Generated 1k/10k/50k/100k/500k file and 10k/100k/500k/1M directory discovery tiers exercise constant-size budget state.",
		owner: "rust",
		evidenceFile: "src-tauri/src/resource_limits.rs",
		evidenceToken: "br_res_006_generated_scale_tiers_keep_budget_state_constant_size",
	},
	{
		id: "BR-SCAN-001",
		description: "A routing directory that cannot be inspected fails closed instead of being silently skipped as non-matching evidence.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_scan_001_unreadable_routing_branch_fails_closed",
	},
	{
		id: "BR-SCAN-002",
		description: "Directory-source traversal is iterative so deeply nested input does not consume the call stack recursively.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_scan_002_directory_source_traversal_is_iterative_for_deep_trees",
	},
	{
		id: "BR-ROUTE-001",
		description: "Repeated routing basenames cannot trigger unbounded candidate-by-file validation; excessive seed counts become explicit ambiguity with no automatic recommendation.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_route_001_repeated_basename_discovery_caps_expensive_candidate_validation",
	},
	{
		id: "BR-ROUTE-002",
		description: "Root-relative ZIP routing requires strong no-prefix exact-file coverage; exact ROOT mapping outranks source-prefix relocation inside one project while generic directory overlap remains weak evidence.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_route_002_strong_exact_root_beats_equal_source_prefix_relocation",
	},
	{
		id: "BR-ROUTE-003",
		description: "A unique strong no-prefix exact ROOT-relative Files match outranks relocated or context-only matches in other open projects; competing strong exact matches remain explicit unless the source uniquely names one project.",
		owner: "node",
		evidenceFile: "scripts/business-rules/project-routing-confidence.test.mts",
		evidenceToken: "BR-ROUTE-003",
	},

	{
		id: "BR-FILE-001",
		description: "Files Apply mutates the project from exact frozen source bytes even if the original external source changes after freezing.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_file_001_frozen_apply_uses_exact_frozen_bytes_after_original_source_changes",
	},
	{
		id: "BR-FILE-002",
		description: "A source change between preview and final freeze invalidates the preview before any project mutation.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_file_002_source_change_before_freeze_is_rejected_before_project_mutation",
	},
	{
		id: "BR-FILE-003",
		description: "Routing evidence changes between preview and final Apply validation invalidate automatic application before mutation.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_file_003_routing_change_before_apply_is_rejected_before_mutation",
	},
	{
		id: "BR-FILE-004",
		description: "An unchanged-only frozen Files Apply is a true no-op and creates no mutation snapshot.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_file_004_unchanged_only_frozen_apply_creates_no_mutation_snapshot",
	},
	{
		id: "BR-FS-001",
		description: "A checked atomic replacement refuses to overwrite a destination that changed immediately before commit.",
		owner: "rust",
		evidenceFile: "src-tauri/src/safe_fs.rs",
		evidenceToken: "br_fs_001_checked_atomic_replace_preserves_concurrent_destination_change",
	},
	{
		id: "BR-FS-002",
		description: "Project parent directories are created component-by-component beneath the canonical project root with reparse/symlink checks.",
		owner: "rust",
		evidenceFile: "src-tauri/src/safe_fs.rs",
		evidenceToken: "br_fs_002_project_parent_creation_builds_only_under_the_canonical_root",
	},
	{
		id: "BR-STAGE-001",
		description: "Files Apply staging uses fresh random non-reparse directories owned by a single operation.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_stage_001_files_apply_staging_is_fresh_unpredictable_and_non_reparse",
	},
	{
		id: "BR-STAGE-002",
		description: "Windows virtual-drop staging uses GUID-backed fresh directories and never reuses predictable tick/counter paths.",
		owner: "node",
		evidenceFile: "scripts/business-rules/patch4-hardening.test.mts",
		evidenceToken: "BR-STAGE-002",
	},
	{
		id: "BR-STORAGE-001",
		description: "Orqeto storage reservations enforce project/global logical quotas, soft-GC thresholds, and physical free-space margin before mutation.",
		owner: "rust",
		evidenceFile: "src-tauri/src/storage.rs",
		evidenceToken: "br_storage_001_quota_boundaries_and_physical_space_fail_before_reservation",
	},
	{
		id: "BR-STORAGE-002",
		description: "Undo/recovery backups use content-addressed shared blobs and retain shared content until the final live reference is gone.",
		owner: "rust",
		evidenceFile: "src-tauri/src/storage.rs",
		evidenceToken: "br_storage_002_shared_blob_reference_is_content_addressed_and_stable",
	},
	{
		id: "BR-STORAGE-003",
		description: "Merged Files-mode Undo entries release intermediate backup blobs that are no longer needed to restore the merged batch.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_storage_003_merged_files_undo_drops_unneeded_intermediate_backup_blob",
	},
	{
		id: "BR-GC-001",
		description: "Garbage collection prioritizes rebuildable/stale data and never selects active Undo, active staging, or recovery-critical storage.",
		owner: "rust",
		evidenceFile: "src-tauri/src/storage.rs",
		evidenceToken: "br_gc_001_gc_priority_never_selects_active_or_recovery_critical_data",
	},
	{
		id: "BR-GC-002",
		description: "Storage cleanup refuses symlink/reparse escape paths and cannot follow stale temporary content outside Orqeto-owned storage.",
		owner: "rust",
		evidenceFile: "src-tauri/src/storage.rs",
		evidenceToken: "br_gc_002_cleanup_refuses_symlink_escape",
	},
	{
		id: "BR-GC-003",
		description: "Garbage collection treats active descendants and ancestors as one protected temporary-storage subtree.",
		owner: "rust",
		evidenceFile: "src-tauri/src/storage.rs",
		evidenceToken: "br_gc_003_active_descendant_protects_its_managed_ancestor",
	},
	{
		id: "BR-RECOVERY-001",
		description: "Recovery-critical snapshots and their referenced blobs are protected from normal garbage collection.",
		owner: "rust",
		evidenceFile: "src-tauri/src/storage.rs",
		evidenceToken: "br_recovery_001_gc_preserves_recovery_critical_snapshot_and_referenced_blob",
	},
	{
		id: "BR-RECOVERY-002",
		description: "Multi-step Undo is journaled and restores sequential replacements exactly to the original pre-operation state.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_recovery_002_multi_undo_restores_sequential_replacements_to_original_state",
	},
	{
		id: "BR-RECOVERY-003",
		description: "An injected Apply failure after a recorded mutation rolls the project back to its exact pre-Apply state.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_recovery_003_apply_failure_after_first_mutation_restores_pre_apply_state",
	},
	{
		id: "BR-RECOVERY-004",
		description: "An injected Undo failure rolls back the partial Undo and leaves the same exact Undo retryable.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_recovery_004_undo_failure_rolls_back_then_allows_exact_retry",
	},
	{
		id: "BR-RECOVERY-005",
		description: "Content-addressed recovery blobs are revalidated against their identifier before Undo/recovery reads them.",
		owner: "rust",
		evidenceFile: "src-tauri/src/storage.rs",
		evidenceToken: "br_recovery_005_blob_identity_validation_rejects_tampered_content",
	},
	{
		id: "BR-RECOVERY-006",
		description: "Recovery may infer a committed file mutation after a crash only when the current destination exactly matches the journaled Orqeto after-state, even if the per-file applied flag was not persisted.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_recovery_006_exact_after_state_recovers_when_applied_flag_was_not_persisted",
	},
	{
		id: "BR-UNDO-001",
		description: "Undo records Created as absence and Modified/Deleted as exact prior bytes, restoring mixed operations exactly.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_undo_001_created_modified_deleted_restore_exact_prior_state",
	},
	{
		id: "BR-UNDO-002",
		description: "Undo refuses to overwrite a user edit when the current file no longer matches the state produced by Orqeto.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_undo_002_user_edit_blocks_undo_without_overwrite",
	},
	{
		id: "BR-UNDO-003",
		description: "A concurrent destination edit immediately before an Undo/recovery restore commit is preserved instead of being overwritten.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_undo_003_concurrent_edit_before_restore_commit_is_preserved",
	},
	{
		id: "BR-STATUS-001",
		description: "Authoritative Files Apply backend results map to exact top-status counters and preserve the backend operation identity.",
		owner: "node",
		evidenceFile: "scripts/business-rules/status-outcome.test.mts",
		evidenceToken: "BR-STATUS-001",
	},
	{
		id: "BR-STATUS-002",
		description: "Mixed changed/unchanged/failed work is reported as partial rather than unconditional success.",
		owner: "node",
		evidenceFile: "scripts/business-rules/status-outcome.test.mts",
		evidenceToken: "BR-STATUS-002",
	},
	{
		id: "BR-STATUS-003",
		description: "A no-op Files Apply never exposes a contextual Undo reference.",
		owner: "node",
		evidenceFile: "scripts/business-rules/status-outcome.test.mts",
		evidenceToken: "BR-STATUS-003",
	},
	{
		id: "BR-STATUS-004",
		description: "Contextual Undo is eligible only while its exact operation ID remains the newest Undo entry.",
		owner: "node",
		evidenceFile: "scripts/business-rules/status-outcome.test.mts",
		evidenceToken: "BR-STATUS-004",
	},
	{
		id: "BR-STATUS-005",
		description: "Apply directory counters are rendered as affected folders with representative plural grammar in both locales.",
		owner: "node",
		evidenceFile: "scripts/business-rules/status-outcome.test.mts",
		evidenceToken: "BR-STATUS-005",
	},
	{
		id: "BR-STATUS-006",
		description: "Routed Files/Git decision and preview states use decision/preview messages and never claim Apply before completion.",
		owner: "node",
		evidenceFile: "scripts/business-rules/status-outcome.test.mts",
		evidenceToken: "BR-STATUS-006",
	},
	{
		id: "BR-VSCODE-001",
		description: "VS Code liveness refresh avoids the permanent PowerShell/CIM process scan and uses cheap adaptive published-state polling.",
		owner: "node",
		evidenceFile: "scripts/business-rules/patch7-performance.test.mts",
		evidenceToken: "BR-VSCODE-001",
	},
	{
		id: "BR-VSCODE-002",
		description: "VS Code forwarding revalidates the published live instance and authoritative project state when a command executes.",
		owner: "node",
		evidenceFile: "scripts/business-rules/patch7-performance.test.mts",
		evidenceToken: "BR-VSCODE-002",
	},
	{
		id: "BR-PERF-001",
		description: "Inactive project tabs do not refresh diagnostic capabilities on every global focus event.",
		owner: "node",
		evidenceFile: "scripts/business-rules/patch7-performance.test.mts",
		evidenceToken: "BR-PERF-001",
	},
	{
		id: "BR-PERF-002",
		description: "Filesystem-heavy cross-project routing is conservatively serialized instead of using unbounded per-tab parallelism.",
		owner: "node",
		evidenceFile: "scripts/business-rules/patch7-performance.test.mts",
		evidenceToken: "BR-PERF-002",
	},
	{
		id: "BR-PERF-003",
		description: "Full-project Download materializes, formats, and writes the large context in the backend without a giant Rust-to-JS-to-Rust string round trip.",
		owner: "node",
		evidenceFile: "scripts/business-rules/patch7-performance.test.mts",
		evidenceToken: "BR-PERF-003",
	},
	{
		id: "BR-PERF-004",
		description: "Release packaging does not reinstall VS Code dependencies and avoids duplicate app TypeScript compilation in the Tauri before-build step.",
		owner: "node",
		evidenceFile: "scripts/business-rules/patch7-performance.test.mts",
		evidenceToken: "BR-PERF-004",
	},
	{
		id: "BR-UI-001",
		description: "Folder, Context, and Apply section expansion plus the selected project-folder action are persisted global UI state shared by every project tab.",
		owner: "node",
		evidenceFile: "scripts/business-rules/patch7-performance.test.mts",
		evidenceToken: "BR-UI-001",
	},
	{
		id: "BR-UI-002",
		description: "Project/destination selection and Git preview remain interactive by suppressing loading overlays and rendering decision dialogs outside inert busy-content subtrees.",
		owner: "node",
		evidenceFile: "scripts/business-rules/context-layout-and-tab-overlay.test.mts",
		evidenceToken: "BR-UI-002",
	},
	{
		id: "BR-ADV-001",
		description: "A 50,000-path manual Context membership remains reference-only and supports selecting small materialization subsets without cached source blobs.",
		owner: "node",
		evidenceFile: "scripts/business-rules/adversarial-final.test.mts",
		evidenceToken: "BR-ADV-001",
	},
	{
		id: "BR-ADV-002",
		description: "Context/routing race defenses revalidate root and membership revisions, ignore evidence, overlapping project access, and stale contextual Undo identity.",
		owner: "node",
		evidenceFile: "scripts/business-rules/adversarial-final.test.mts",
		evidenceToken: "BR-ADV-002",
	},
	{
		id: "BR-ADV-003",
		description: "Fault injection across snapshot/journal/temp/commit/recovery boundaries fails closed without losing the pre-operation or user-modified state.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_adv_003_fault_injection_boundaries_fail_closed",
	},
	{
		id: "BR-ADV-004",
		description: "The final path and ZIP security corpus rejects absolute/traversal/unsafe alias inputs while accepting safe Unicode project-relative names.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_adv_004_zip_and_delete_manifest_path_corpus",
	},
	{
		id: "BR-ADV-005",
		description: "The strict Git patch corpus rejects binary, copy, mode, symlink, submodule, traversal, quoted, and backslash path forms that the delivery contract forbids.",
		owner: "rust",
		evidenceFile: "src-tauri/src/git_context.rs",
		evidenceToken: "br_adv_005_git_unsupported_operation_and_path_corpus",
	},
	{
		id: "BR-ADV-006",
		description: "Permanent documentation describes the final implementation without temporary robustness-roadmap language, final adversarial commands are wired, and ZIP support remains present.",
		owner: "node",
		evidenceFile: "scripts/business-rules/adversarial-final.test.mts",
		evidenceToken: "BR-ADV-006",
	},
] as const
