include!("diagnostics/model_and_limits.rs");
include!("diagnostics/eslint_model.rs");
include!("diagnostics/config_discovery.rs");
include!("diagnostics/bounded_io.rs");
include!("diagnostics/path_validation.rs");
include!("diagnostics/lint_fix_plan.rs");
include!("diagnostics/lint_fix_apply.rs");
include!("diagnostics/context_report.rs");
include!("diagnostics/validation_commands.rs");
