mod config_database;
mod context_redaction;
mod diagnostics;
mod external_integration;
mod git_context;
mod native_drop;
mod operation_id;
mod overlay;
mod project_ignore;
mod process_tree;
mod project_logs;
mod resource_limits;
mod runtime_utils;
mod safe_fs;
mod storage;

include!("lib/core_types_and_state.rs");
include!("lib/context_text.rs");
include!("lib/windows_process.rs");
include!("lib/vscode_integration.rs");
include!("lib/explorer.rs");
include!("lib/context_materialization.rs");
include!("lib/context_tree.rs");
include!("lib/export.rs");
include!("lib/app_bootstrap.rs");
