export const ORQETO_REGISTRY_KEY = String.raw`HKCU\Software\Orqeto\Orqeto Dev`
export const EXECUTABLE_VALUE_NAME = "ExecutablePath"
export const INTEGRATION_STATE_VALUE_NAME = "IntegrationState"
export const RUNNING_CONTEXT_KEY = "orqetoDev.isRunning"
export const PROJECT_OPEN_CONTEXT_KEY = "orqetoDev.projectOpen"
export const PROJECT_BUSY_CONTEXT_KEY = "orqetoDev.projectBusy"
export const IGNORE_MODE_CONTEXT_KEY = "orqetoDev.ignoreMode"
export const LOCALE_PT_BR_CONTEXT_KEY = "orqetoDev.localePtBR"
export const LOCALE_ENGLISH_CONTEXT_KEY = "orqetoDev.localeEnglish"
export const ALLOW_OPEN_SUBFOLDERS_CONTEXT_KEY = "orqetoDev.allowOpenSubfolders"
export const OPEN_PROJECT_ROOT_PATHS_CONTEXT_KEY = "orqetoDev.openProjectRootPaths"
export const WORKSPACE_ROOT_EXACTLY_OPEN_CONTEXT_KEY = "orqetoDev.workspaceRootExactlyOpen"
export const FORWARD_ONLY_ARG = "--orqeto-dev-forward-only"
export const FORWARD_ONLY_NO_PRIMARY_EXIT_CODE = 73
export const FORWARD_DELIVERY_TIMEOUT_MS = 10_000
export const ACTIVE_STATE_REFRESH_INTERVAL_MS = 5_000
export const INACTIVE_STATE_REFRESH_INTERVAL_MS = 30_000
export const REGISTRY_QUERY_TIMEOUT_MS = 5_000
