import type { BusinessRuleDefinition } from "./types.mts"

export const rules: readonly BusinessRuleDefinition[] = [
	{
		id: "BR-CTX-001",
		description: "Active manual Context keeps path references and discards source content from long-lived selection state.",
		owner: "node",
		evidenceFile: "scripts/business-rules/context-selection.test.mts",
		evidenceToken: "BR-CTX-001",
	},
	{
		id: "BR-CTX-002",
		description: "Re-adding an already selected path reports it as already present and never replaces selection state with supplied content.",
		owner: "node",
		evidenceFile: "scripts/business-rules/context-selection.test.mts",
		evidenceToken: "BR-CTX-002",
	},
	{
		id: "BR-CTX-003",
		description: "Re-sending a selection may add newly discovered paths while preserving deduplication of existing paths.",
		owner: "node",
		evidenceFile: "scripts/business-rules/context-selection.test.mts",
		evidenceToken: "BR-CTX-003",
	},
	{
		id: "BR-CTX-004",
		description: "Context materialization reads the current filesystem bytes rather than selection-time bytes.",
		owner: "rust",
		evidenceFile: "src-tauri/src/lib.rs",
		evidenceToken: "br_ctx_004_materialization_reads_current_content_instead_of_selection_time_content",
	},
	{
		id: "BR-CTX-005",
		description: "Manual Context selection discovers path membership without opening or decoding source file bodies.",
		owner: "rust",
		evidenceFile: "src-tauri/src/lib.rs",
		evidenceToken: "br_ctx_005_selection_keeps_binary_file_as_reference_without_materializing_body",
	},
	{
		id: "BR-CTX-006",
		description: "Missing or newly ignored selected members are unavailable at materialization and stale selection-time bytes are never substituted.",
		owner: "rust",
		evidenceFile: "src-tauri/src/lib.rs",
		evidenceToken: "br_ctx_006_unavailable_selected_members_never_use_stale_content",
	},
	{
		id: "BR-CTX-007",
		description: "Files created after a folder was selected remain outside active Context until that folder or file is explicitly sent again.",
		owner: "node",
		evidenceFile: "scripts/business-rules/context-selection.test.mts",
		evidenceToken: "BR-CTX-007",
	},
	{
		id: "BR-CTX-008",
		description: "Manual Clear discards active Context even when selected paths are unavailable, while skipping incomplete history snapshots.",
		owner: "node",
		evidenceFile: "scripts/business-rules/generated-context-workflow.test.mts",
		evidenceToken: "BR-CTX-008",
	},
	{
		id: "BR-CTX-009",
		description: "Generated Commit, TypeScript, and ESLint reports auto-copy by default while retaining manual Copy and preserving generated content on clipboard failure.",
		owner: "node",
		evidenceFile: "scripts/business-rules/generated-context-workflow.test.mts",
		evidenceToken: "BR-CTX-009",
	},
	{
		id: "BR-CTX-010",
		description: "Full-project context discovery is explicit: entering Full mode performs no scan, Scan records the filtered path snapshot and size, and Copy/Download stay disabled until that scan exists.",
		owner: "node",
		evidenceFile: "scripts/business-rules/generated-context-workflow.test.mts",
		evidenceToken: "BR-CTX-010",
	},
	{
		id: "BR-CTX-011",
		description: "Context output redacts env-like values, sensitive config fields, URL credentials/query secrets, and high-confidence token signatures before AI exposure, including Git Commit Context.",
		owner: "node",
		evidenceFile: "scripts/business-rules/context-redaction.test.mts",
		evidenceToken: "BR-CTX-011",
	},
	{
		id: "BR-CTX-012",
		description: "AI-delivered Apply protects secret-bearing files: prompts mark them informational-only, Files mode skips protected writes/deletes with counters, and Git mode rejects protected patches.",
		owner: "node",
		evidenceFile: "scripts/business-rules/context-redaction.test.mts",
		evidenceToken: "BR-CTX-012",
	},
	{
		id: "BR-HISTORY-001",
		description: "Routine Context history listing transports metadata only and never includes archived content blobs.",
		owner: "rust",
		evidenceFile: "src-tauri/src/config_database.rs",
		evidenceToken: "br_history_001_history_listing_returns_metadata_without_content_blob",
	},
	{
		id: "BR-HISTORY-002",
		description: "A single Context history snapshot is loaded lazily and reproduced byte-for-byte when requested.",
		owner: "rust",
		evidenceFile: "src-tauri/src/config_database.rs",
		evidenceToken: "br_history_002_history_content_is_loaded_lazily_and_exactly",
	},
	{
		id: "BR-HISTORY-003",
		description: "Routine React history state is metadata-only and copy loads one archived snapshot lazily on demand.",
		owner: "node",
		evidenceFile: "scripts/business-rules/history-lazy.test.mts",
		evidenceToken: "BR-HISTORY-003",
	},
	{
		id: "BR-HISTORY-004",
		description: "History download resolves archived content inside the Rust backend instead of routing the blob through React state.",
		owner: "node",
		evidenceFile: "scripts/business-rules/history-lazy.test.mts",
		evidenceToken: "BR-HISTORY-004",
	},
	{
		id: "BR-HISTORY-005",
		description: "Applied-source history records a human-readable origin and content fingerprint, warns before older retained content is reused, and treats the newest Git patch as already applied only when the recorded post-apply state still matches.",
		owner: "node",
		evidenceFile: "scripts/business-rules/apply-history-safety.test.mts",
		evidenceToken: "BR-HISTORY-005",
	},
	{
		id: "BR-HISTORY-006",
		description: "Custom, Commit, Full-project, TypeScript, Lint Fix, ESLint, and Test contexts share one persisted typed per-project Context history bounded by Settings.",
		owner: "node",
		evidenceFile: "scripts/business-rules/history-persistence.test.mts",
		evidenceToken: "BR-HISTORY-006",
	},
	{
		id: "BR-HISTORY-007",
		description: "Application history and its exact Undo snapshots remain persistent across normal app restart and project-tab close/reopen up to the configured limit.",
		owner: "node",
		evidenceFile: "scripts/business-rules/history-persistence.test.mts",
		evidenceToken: "BR-HISTORY-007",
	},
	{
		id: "BR-HISTORY-008",
		description: "Context history is exposed once beside Create context without reserving a bottom row, while Custom Copy/Download/Clear stay in one action row.",
		owner: "node",
		evidenceFile: "scripts/business-rules/history-persistence.test.mts",
		evidenceToken: "BR-HISTORY-008",
	},
	{
		id: "BR-DOCS-001",
		description: "Permanent business documentation lives under docs/docs.md and documents the aggregate project Test-command contract for AI-assisted validation.",
		owner: "node",
		evidenceFile: "scripts/business-rules/documentation-layout.test.mts",
		evidenceToken: "BR-DOCS-001",
	},
	{
		id: "BR-DOCS-002",
		description: "Permanent documentation keeps one canonical business-rules source and covers conditional AI test integration, in-app execution trust, repeated-ZIP no-op semantics, and global button hover affordance.",
		owner: "node",
		evidenceFile: "scripts/business-rules/documentation-layout.test.mts",
		evidenceToken: "BR-DOCS-002",
	},
]
