import type { BusinessRuleDefinition } from "./types.mts"

export const rules: readonly BusinessRuleDefinition[] = [
	{
		id: "BR-ROUTE-001",
		description: "Repeated routing basenames cannot trigger unbounded candidate-by-file validation; excessive seed counts become explicit ambiguity with no automatic recommendation.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_route_001_repeated_basename_discovery_caps_expensive_candidate_validation",
	},
	{
		id: "BR-ROUTE-002",
		description: "Root-relative ZIP routing requires strong no-prefix exact-file coverage; exact ROOT mapping outranks source-prefix relocation inside one project while generic directory overlap remains weak evidence.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_route_002_strong_exact_root_beats_equal_source_prefix_relocation",
	},
	{
		id: "BR-ROUTE-003",
		description: "Files and Git Apply prepare only the initiating project ROOT, never comparing the input to other open projects.",
		owner: "node",
		evidenceFile: "scripts/business-rules/project-routing-confidence.test.mts",
		evidenceToken: "BR-ROUTE-003",
	},
	{
		id: "BR-ROUTE-004",
		description: "A ZIP top-level folder that mirrors the archive name is treated as packaging when stripping it yields strong root-file coverage, while generic directory-only overlap cannot make an unrelated project concrete.",
		owner: "rust",
		evidenceFile: "src-tauri/src/overlay.rs",
		evidenceToken: "br_route_004_zip_archive_envelope_rejects_generic_directory_only_foreign_match",
	},
	{
		id: "BR-ROUTE-005",
		description: "Local destination ambiguity offers only in-project paths and an explicit safe ROOT fallback; no project-level selector is used.",
		owner: "node",
		evidenceFile: "scripts/business-rules/project-routing-confidence.test.mts",
		evidenceToken: "BR-ROUTE-005",
	},
	{
		id: "BR-ROUTE-006",
		description: "Direct tab drops and ordinary Apply-zone drops both target only their initiating rooted tab, while valid drop surfaces advertise copy-drop affordance.",
		owner: "node",
		evidenceFile: "scripts/business-rules/tab-apply-drop.test.mts",
		evidenceToken: "BR-ROUTE-006",
	},
	{
		id: "BR-ROUTE-007",
		description: "Excessive internal destination ambiguity never bypasses safety limits or falls back to ROOT automatically.",
		owner: "node",
		evidenceFile: "scripts/business-rules/project-routing-confidence.test.mts",
		evidenceToken: "BR-ROUTE-007",
	},
	{
		id: "BR-ROUTE-008",
		description: "Files preparation against the initiating project surfaces malformed input and invalid manifest errors instead of replacing them with no-destination messages.",
		owner: "node",
		evidenceFile: "scripts/business-rules/delete-manifest-routing.test.mts",
		evidenceToken: "BR-ROUTE-008",
	},
	{
		id: "BR-STATUS-001",
		description: "Authoritative Files Apply backend results map to exact top-status counters and preserve the backend operation identity.",
		owner: "node",
		evidenceFile: "scripts/business-rules/status-outcome.test.mts",
		evidenceToken: "BR-STATUS-001",
	},
	{
		id: "BR-STATUS-002",
		description: "Mixed changed/unchanged/failed work is reported as partial rather than unconditional success.",
		owner: "node",
		evidenceFile: "scripts/business-rules/status-outcome.test.mts",
		evidenceToken: "BR-STATUS-002",
	},
	{
		id: "BR-STATUS-003",
		description: "A no-op Files Apply never exposes a contextual Undo reference.",
		owner: "node",
		evidenceFile: "scripts/business-rules/status-outcome.test.mts",
		evidenceToken: "BR-STATUS-003",
	},
	{
		id: "BR-STATUS-004",
		description: "Contextual Undo is eligible only while its exact operation ID remains the newest Undo entry.",
		owner: "node",
		evidenceFile: "scripts/business-rules/status-outcome.test.mts",
		evidenceToken: "BR-STATUS-004",
	},
	{
		id: "BR-STATUS-005",
		description: "Apply directory counters are rendered as affected folders with representative plural grammar in both locales.",
		owner: "node",
		evidenceFile: "scripts/business-rules/status-outcome.test.mts",
		evidenceToken: "BR-STATUS-005",
	},
	{
		id: "BR-STATUS-006",
		description: "Routed Files/Git decision and preview states use decision/preview messages and never claim Apply before completion.",
		owner: "node",
		evidenceFile: "scripts/business-rules/status-outcome.test.mts",
		evidenceToken: "BR-STATUS-006",
	},
	{
		id: "BR-STATUS-007",
		description: "Project-local action feedback uses one notice surface so a newer Apply, Dev Ignore, Context, validation, or related action replaces the previous message instead of stacking another banner.",
		owner: "node",
		evidenceFile: "scripts/business-rules/status-outcome.test.mts",
		evidenceToken: "BR-STATUS-007",
	},
	{
		id: "BR-STATUS-008",
		description: "Cancellable validation work has its own client operation-ID namespace without widening authoritative user-visible operation outcome types.",
		owner: "node",
		evidenceFile: "scripts/business-rules/status-outcome.test.mts",
		evidenceToken: "BR-STATUS-008",
	},
]
