import type { BusinessRuleDefinition } from "./types.mts"

export const rules: readonly BusinessRuleDefinition[] = [
	{
		id: "BR-WIN-001",
		description: "Valid native drag-enter and Explorer/VS Code external actions transiently raise and focus Orqeto without leaving the window permanently topmost.",
		owner: "node",
		evidenceFile: "scripts/business-rules/windows-external-focus.test.mts",
		evidenceToken: "BR-WIN-001",
	},
	{
		id: "BR-WIN-002",
		description: "Windows integration registration removes Orqeto-owned legacy shell verbs before writing the canonical Explorer entries so upgrades converge without duplicate menu items.",
		owner: "node",
		evidenceFile: "scripts/business-rules/windows-external-focus.test.mts",
		evidenceToken: "BR-WIN-002",
	},
	{
		id: "BR-WIN-003",
		description: "Refreshing Windows native drop targets never revokes an IDropTarget while a supported OLE drag is active, so an accepted drag keeps its drop effect until leave or drop.",
		owner: "node",
		evidenceFile: "scripts/business-rules/windows-external-focus.test.mts",
		evidenceToken: "BR-WIN-003",
	},
	{
		id: "BR-VSCODE-001",
		description: "VS Code liveness refresh avoids the permanent PowerShell/CIM process scan and uses cheap adaptive published-state polling.",
		owner: "node",
		evidenceFile: "scripts/business-rules/patch7-performance.part-1.mts",
		evidenceToken: "BR-VSCODE-001",
	},
	{
		id: "BR-VSCODE-002",
		description: "VS Code forwarding revalidates the published live instance and authoritative project state when a command executes.",
		owner: "node",
		evidenceFile: "scripts/business-rules/patch7-performance.part-1.mts",
		evidenceToken: "BR-VSCODE-002",
	},
	{
		id: "BR-VSCODE-003",
		description: "VS Code Context actions remain available for every open non-busy project regardless of the visible Context generator, then focus the owner and switch it to Project > Custom before add/copy/remove.",
		owner: "node",
		evidenceFile: "scripts/business-rules/vscode-create-mode-and-typecheck-selection.test.mts",
		evidenceToken: "BR-VSCODE-003",
	},
	{
		id: "BR-DIAG-001",
		description: "Type Check and ESLint remain standardized Orqeto diagnostics while Lint Fix uses an explicit project command when configured and the safe internal ESLint fixer otherwise.",
		owner: "node",
		evidenceFile: "scripts/business-rules/lint-fix.test.mts",
		evidenceToken: "BR-DIAG-001",
	},
	{
		id: "BR-DIAG-002",
		description: "Test is exposed only through explicit orqetoDev.validation.test configuration, refreshes dynamically, and package configuration cannot override standardized Type Check or ESLint reports.",
		owner: "node",
		evidenceFile: "scripts/business-rules/custom-validation-commands.part-1.mts",
		evidenceToken: "BR-DIAG-002",
	},
	{
		id: "BR-DIAG-003",
		description: "Custom Lint Fix and Test commands require exact-command session trust, bounded execution, and preserve stdout/stderr plus exit metadata as persistent Copy/Download validation contexts even on non-zero exit.",
		owner: "node",
		evidenceFile: "scripts/business-rules/custom-validation-commands.part-1.mts",
		evidenceToken: "BR-DIAG-003",
	},
	{
		id: "BR-DIAG-004",
		description: "Lint Fix and Test expose cancellation while their executable work is active; cancellation stops the backend process tree where applicable and discards the pending validation report.",
		owner: "node",
		evidenceFile: "scripts/business-rules/custom-validation-commands.part-2.mts",
		evidenceToken: "BR-DIAG-004",
	},
	{
		id: "BR-DIAG-005",
		description: "Execution trust and retained-source reapply confirmations use Orqeto in-app dialogs; diagnostic root trust and exact custom-command trust are remembered only for the current app session.",
		owner: "node",
		evidenceFile: "scripts/business-rules/custom-validation-commands.part-2.mts",
		evidenceToken: "BR-DIAG-005",
	},
	{
		id: "BR-LOG-001",
		description: "Development-log execution is explicit-only, exact-command trust-gated, canonical-root scoped, background captured, process-tree stoppable, secret-redacted, and bounded.",
		owner: "node",
		evidenceFile: "scripts/business-rules/project-logs.test.mts",
		evidenceToken: "BR-LOG-001",
	},
	{
		id: "BR-LOG-002",
		description: "Logs exposes Start/Stop/live output/Copy/Download/Clear with persisted default-on copy-clear, inactive-tab polling suspension, and lifecycle cleanup of owned development processes.",
		owner: "node",
		evidenceFile: "scripts/business-rules/project-logs.test.mts",
		evidenceToken: "BR-LOG-002",
	},
	{
		id: "BR-PERF-001",
		description: "Inactive project tabs do not refresh diagnostic capabilities on every global focus event.",
		owner: "node",
		evidenceFile: "scripts/business-rules/patch7-performance.part-1.mts",
		evidenceToken: "BR-PERF-001",
	},
	{
		id: "BR-PERF-002",
		description: "Apply prepares only the initiating project ROOT and never launches filesystem discovery across the other open tabs.",
		owner: "node",
		evidenceFile: "scripts/business-rules/patch7-performance.part-1.mts",
		evidenceToken: "BR-PERF-002",
	},
	{
		id: "BR-PERF-003",
		description: "Full-project Download materializes, formats, and writes the large context in the backend without a giant Rust-to-JS-to-Rust string round trip.",
		owner: "node",
		evidenceFile: "scripts/business-rules/patch7-performance.part-1.mts",
		evidenceToken: "BR-PERF-003",
	},
	{
		id: "BR-PERF-004",
		description: "Release packaging does not reinstall VS Code dependencies and avoids duplicate app TypeScript compilation in the Tauri before-build step.",
		owner: "node",
		evidenceFile: "scripts/business-rules/patch7-performance.part-1.mts",
		evidenceToken: "BR-PERF-004",
	},
	{
		id: "BR-PERF-005",
		description: "The production frontend splits third-party dependencies into bounded vendor chunks instead of suppressing Vite chunk-size warnings.",
		owner: "node",
		evidenceFile: "scripts/business-rules/patch7-performance.part-2.mts",
		evidenceToken: "BR-PERF-005",
	},
	{
		id: "BR-UI-001",
		description: "Folder, Context, and Apply section expansion plus the selected project-folder action are persisted global UI state shared by every project tab.",
		owner: "node",
		evidenceFile: "scripts/business-rules/patch7-performance.part-2.mts",
		evidenceToken: "BR-UI-001",
	},
	{
		id: "BR-UI-002",
		description: "Project/destination selection and Git preview remain interactive by suppressing loading overlays and rendering decision dialogs outside inert busy-content subtrees.",
		owner: "node",
		evidenceFile: "scripts/business-rules/context-layout-and-tab-overlay.test.mts",
		evidenceToken: "BR-UI-002",
	},
	{
		id: "BR-UI-003",
		description: "Every enabled button exposes pointer and visual hover affordance on hover-capable fine-pointer devices without applying hover styling to disabled controls.",
		owner: "node",
		evidenceFile: "scripts/business-rules/ui-affordances.test.mts",
		evidenceToken: "BR-UI-003",
	},
	{
		id: "BR-UI-004",
		description: "Shared in-app dialogs expose modal semantics, Escape cancellation, keyboard focus trapping, and previous-focus restoration.",
		owner: "node",
		evidenceFile: "scripts/business-rules/ui-affordances.test.mts",
		evidenceToken: "BR-UI-004",
	},
]
